### PR TITLE
Make ndenv_npm idempotent

### PR DESCRIPTION
**Pull request by ranjib**
Current implementation of ndenv_npm is not idempotent, it install declared packaged everytime chef runs. This PR fixes that, along side:
- get rid of subclassing chef's package class, its not needed
- use chef's lwrp provider DSL

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi,

I had some fixes on this branch https://github.com/Numergy/ndenv-cookbook/tree/ranjib-npm_package_why_run.
There were foodcritic, rubocop and kitchen problems. I fixed it. Have a look and tell me if it's ok for you ;)

Regards

**Comment by PierreRambaud** [comment]
I make you a PR on your PR :)

**Comment by ranjib** [comment]
@PierreRambaud i reverted your patch. i didnt like @new_resource access where theres an attribute reader available (new_resource) and the rescue nil logic style for detecting version of an existing npm package (if `npm ls` fails, we should not try to parse the output)

**Comment by PierreRambaud** [comment]
Without this patch, your PR is invalid and cause some bugs. If you run tests, you will see that.

**Comment by PierreRambaud** [comment]
I commit some changes on my branch, you can have a look

**Comment by Sliim** [comment]
Hi!

I'm globally ok with this PR, can you just fix on your branch:
- foodcritic (FC023)
- rubocop (7 offenses)

Do not take care of kitchen tests on travis, I will remove them after merging (they no longer works).

Also, converging an instance with test-kitchen fails because provider `Chef::Provider::Package::NdenvNpm` no longer exists. Can you fix this in `resources/npm.rb`?

Thanks

**Comment by ranjib** [comment]
@Sliim if i fix FC023 we'll loose the ability to detect and bypass it via why run. so i wont fix that. i'll address the rubocop and provider class loading issue.
thanks for the review

**Comment by Sliim** [comment]
Thank you for your fixes!
Ok for FC023, I will exclude this rule.

There is another problem, that we can see with kitchen tests: `bower` package is not installed for node version `v0.10.20` after converge.
After debugging, I see that following commands return a different exitcode:
```
~# /opt/ndenv/versions/v0.10.20/bin/npm -g -j ls package; echo $?
{}
0
~# /opt/ndenv/versions/v0.10.26/bin/npm -g -j ls package; echo $?
{}
1
```

So I think that checking exitcode of these commands is not the good way to determine if package is installed. Maybe we can check if JSON output is empty instead?

**Comment by Sliim** [comment]
ping @ranjib

**Pull request merged**
